### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by HomingChen**
彭彭老師您好，我是鴻銘；目前依part1指引，部屬到以下三個網址，雖然好像還有蠻多細節沒有補上，還請老師確認，謝謝
http://3.229.155.34:3000/api/attractions?page=1
http://3.229.155.34:3000/api/attractions?page=0&keyword=萬華
http://3.229.155.34:3000/api/attraction/3
http://3.229.155.34:3000/api/categories

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your live URLs are broken.

**Comment by HomingChen** [comment]
thanks reminding, just used "nohup" to run app in background, also updated the error handler.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by HomingChen** [comment]
sorry... i thought reviewers would keep having their review right till the request was ended. just sent another review request.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. `nextPage` field of http://3.229.155.34:3000/api/attractions?page=4 and http://3.229.155.34:3000/api/attractions?page=1&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80 should be null because they are the last page of results.
2. `data` in http://3.229.155.34:3000/api/categories should be a string array containing every category name as array elements. For example: ["category 1", "category 2", ...]
3. use `LIMIT` in SQL to do pagination than get ALL DATA and do it in your own code.

Solve issues and re-request review.

**Comment by HomingChen** [comment]
appreciated for reviewing, issues were modified as the link below:
1. `nextPage` will be null if there is no more data
http://3.229.155.34:3000/api/attractions?page=4 
http://3.229.155.34:3000/api/attractions?page=1&keyword=藝文館所
2. changed `data` format in catagry 
http://3.229.155.34:3000/api/categories
3. use `LIMIT` in MySQL to get 12 data rather then get all data at once
image

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
